# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamnumber', models.IntegerField()),
                ('roundnumber', models.IntegerField()),
                ('servicename', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'logininfo',
            },
        ),
    ]
