# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_auto_20170312_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
